### ISSUE TITLE
добавить базовые pre-commit через gh-actions

### ISSUE THREAD

**Issue by vtrokhymenko** [newsviz/newsviz#41]
[gh-actions](https://github.com/features/actions) созданы для того, чтобы при push и/или pr (это все настраиваемо в `.github/workflows`) выполнялись определенные действия, к примеру, запустить проверку black, flake8, isort и даже  выполнить некий deploy итп

предлагаю для начала через `.pre-commit-config.yaml` (созданный на самом верхнем уровне репозитория) добавить:
* [isort](https://github.com/timothycrosley/isort) – поможет более правильнее сортировать все import`s (примеры можете посмотерть по ссылке)
* [black](https://github.com/psf/black) – code formatter для python. с коробки уже хорошо настроен. есть предложение добавить в качестве аргумента только `--line-length=119`
* некоторые [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) (полный их список по ссылке):
  * `check-json` – attempts to load all json files to verify syntax
  * `check-yaml` – attempts to load all yaml files to verify syntax
  * `detect-private-key` – checks for the existence of private keys
  * `requirements-txt-fixer` – sorts entries in `requirements.txt` and removes incorrect entry for `pkg-resources==0.0.0`
  * `end-of-file-fixer` – makes sure files end in a newline and only a newline
  * `trailing-whitespace` с аргументом `--markdown-linebreak-ext=md` – trims trailing whitespace.
  * <ваш_hook>

в конце, в `CONTRIBUTING.md` нужно добавить как выполнять `pre-commit` у себя на машине:
* `$ pip install pre-commit`
* `$ pre-commit run -a` – полсе этого, все фалйы будут автоматически исправлены по канонам `pre-commit-config`

---
пример `.pre-commit-config.yaml`
```
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
```

пример `.github/workflows/pre-commit.yml`
```
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set python
        uses: actions/setup-python@v2.1.4

      - name: pre-commit-action
        uses: pre-commit/action@v2.0.0
```
