### ISSUE TITLE
добавить code scanning alerts

### ISSUE THREAD

**Issue by vtrokhymenko** [newsviz/newsviz#42]
[code scanning alerts](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) помогает проанализировать код на github как на различные уязвимости безопасности, так и  на ошибки кодирования итд через автоматический cron, так и на push/pr

----
пример `.github/workflows/codeql-analysis.yml`
```
name: codeql

on:
  push:
    branches: master
  pull_request:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  analyse:
    name: analyse
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    # Initializes the CodeQL tools for scanning.
    - name: initialize codeql
      uses: github/codeql-action/init@v1
      # Override language selection by uncommenting this and choosing your languages
#       with:
#         languages: go, javascript, csharp, python, cpp, java

    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
    - name: autobuild
      uses: github/codeql-action/autobuild@v1

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 https://git.io/JvXDl

    # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
    #    and modify them (or add more) to build your code if your project
    #    uses a compiled language

    #- run: |
    #   make bootstrap
    #   make release

    - name: perform codeql analysis
      uses: github/codeql-action/analyze@v1
```
